input_features:
  - name: image_id
    type: image
    preprocessing:
      height: 224
      width: 224
      num_channels: 3
    encoder:
      type: stacked_cnn
      conv_layers:
        - num_filters: 32
          filter_size: 3
          activation: relu
          padding: same
        - num_filters: 32
          filter_size: 3
          activation: relu
          padding: same
        - pool_size: 2
          pool_stride: 2  
        - dropout: 0.25
        - num_filters: 64
          filter_size: 3
          activation: relu
          padding: same
        - num_filters: 64
          filter_size: 3
          activation: relu
          padding: same
        - pool_size: 2
          pool_type: max
          pool_stride: 1  
        - dropout: 0.40
      fc_layers:
        - output_size: 128
          activation: relu
          dropout: 0.5

output_features:
  - name: label
    type: category
    
preprocessing:
  split:
    type: fixed
    column: split

training:
  epochs: 50
  optimizer:
    type: adam
  learning_rate_scheduler:
    type: reduce_on_plateau
    factor: 0.5
    patience: 5

data_augmentation:
  image:
    rotation_range: 10
    zoom_range: 0.1
    width_shift_range: 0.1
    height_shift_range: 0.1
    horizontal_flip: false
    vertical_flip: false
