input_features:
  - name: image_id
    type: image
    preprocessing:
      height: 128  # Increased from 75 to avoid excessive reduction
      width: 128   # Increased from 100 to avoid excessive reduction
      num_channels: 3
      normalization: standard
    encoder:
      type: stacked_cnn
      conv_layers:
        - num_filters: 32
          filter_size: [3, 3]
          activation: relu
          padding: same
        - num_filters: 32
          filter_size: [3, 3]
          activation: relu
          padding: same
        - pool_size: [2, 2]
          pool_type: max
          pool_stride: 2  # Explicitly set to clarify reduction rate
        - dropout: 0.25
        - num_filters: 64
          filter_size: [3, 3]
          activation: relu
          padding: same
        - num_filters: 64
          filter_size: [3, 3]
          activation: relu
          padding: same
        - pool_size: [2, 2]
          pool_type: max
          pool_stride: 2  # Explicitly set to clarify reduction rate
        - dropout: 0.40
      fc_layers:
        - output_size: 128
          activation: relu
          dropout: 0.5

output_features:
  - name: label
    type: category
    num_classes: 7

preprocessing:
  split:
    type: fixed
    column: split

training:
  batch_size: 10
  epochs: 50
  optimizer:
    type: adam
  learning_rate_scheduler:
    type: reduce_on_plateau
    factor: 0.5
    patience: 5

trainer:
  early_stop: 10
  metrics:
    - accuracy
  loss: categorical_crossentropy

data_augmentation:
  image:
    rotation_range: 10
    zoom_range: 0.1
    width_shift_range: 0.1
    height_shift_range: 0.1
    horizontal_flip: false
    vertical_flip: false